info:
  component: stationerycontrol-institution-api

server:
  port: 8085
  servlet:
    context-path: /api

spring:
  application:
    name: stationerycontrol-institution-api
  profiles:
    active: dev
